language: ruby
cache: bundler
install: bundle install --without development --deployment --jobs=3 --retry=3
rvm:
  - "2.2.2"
before_script:
  - cd test/rails_app/
  - RAILS_ENV=test bundle exec rake db:migrate db:fixtures:load
  - cd ../..
script:
  - bundle exec rake test
